name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-16.04

    services:
      pg:
        image: postgres:${{ matrix.pg }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      fail-fast: false
      matrix:
        pg:
          - 8.4
          - 9.0
          - 9.1
          - 9.2
          - 9.3
          - 9.4
          - 9.5
          - 9.6
          - 10
          - 11
          - 12
          - 13

    steps:
      - run: psql postgresql://postgres:postgres@localhost -c "SELECT now()"
